version: '3.8'

services:
  ### Dev Environment as Containerized Service ###
  # Every shell spawned (ie shell for running commands in postStartCommand list of devcontainer.json,
  # or shells opened manulaly through vscode UI) connect to this container (like remote shell connection).
  my_dev_container:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        # Python version to use (ie 3.10, 3.8)
        VARIANT: "3.10"

    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity  # should result in an open shell

    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode
